- hosts: app
  become: true
  tasks:
    - name: init docker centos
      package:
        name: docker
        state: present

- hosts: database
  gather_facts: no
  become: true
  tasks:
    - name: init postgresql-server
      apt:
        name: postgresql={{ var1 }}
        state: present

    - name: change data directory
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        search_string: 'data_directory'
        line: 'data_directory = {{ var2 }}'
        state: present

    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
